[project]
src = "src"
out = "out"
dot_env = ".env"

# TOP LEVEL
[networks.contracts.price_feed]
deployer_script = "script/deploy_mocks.py"

[networks.contracts.buy_me_a_coffee]
deployer_script = "script/deploy.py"

# NETWORK SPECIFIC
[networks.sepolia]
url = "$SEPOLIA_RPC_URL"
save_to_db = false
default_account_name = "metamask_dev"
explorer_uri = "https://eth-sepolia.blockscout.com/"
explorer_type = "blockscout"

# [networks.pyevm.contracts.price_feed]
# deployer_script = "script/deploy_mocks.py"

[networks.sepolia.contracts.price_feed]
address = "0x694AA1769357215DE4FAC081bf1f309aDC325306"
deployer_script = "script/deploy_mocks.py"

[networks.anvil]
url = "http://127.0.0.1:8545"
chain_id = 31337
save_to_db = true
default_account_name = "anvil0"
unsafe_password_file = "$ANVIL0_PASSWORD_FILE"
prompt_live = false

# You can view all configuration options at https://cyfrin.github.io/moccasin/all_moccasin_toml_parameters.html
